name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  node_version: 16
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: yarn
      - run: yarn install
      - run: yarn lint
      - run: yarn test --watchAll=false
      - run: yarn build
      - run: yarn analyze
      - uses: actions/upload-artifact@v2
        with:
          name: analyze
          path: analyze.html
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: yarn
      - run: npm install -g firebase-tools
      - run: yarn install
      - run: yarn build
        env:
          REACT_APP_BACKEND_ORIGIN: ${{ secrets.REACT_APP_BACKEND_ORIGIN }}
          REACT_APP_DEBUG_TRANSLATION: ${{ secrets.REACT_APP_DEBUG_TRANSLATION }}
      - run: firebase deploy --project=$FIREBASE_PROJECT --token=$FIREBASE_TOKEN
        env:
          FIREBASE_PROJECT: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
