name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.5
      - run: npm update -g
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn lint
      - run: yarn test --watchAll=false
      - run: yarn build
      - run: yarn analyze
      - uses: actions/upload-artifact@v2
        with:
          name: analyze
          path: analyze.html
  deploy-staging:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15.5
      - run: npm update -g
      - run: npm install -g firebase-tools
      - run: yarn install
      - run: yarn build
        env:
          REACT_APP_BACKEND_ORIGIN: ${{ secrets.REACT_APP_BACKEND_ORIGIN }}
      - run: firebase deploy --project=$FIREBASE_PROJECT --token=$FIREBASE_TOKEN
        env:
          FIREBASE_PROJECT: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  deploy-production:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - run: echo TODO